server:
  port: 8080

# 뷰 경로 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    response-cache-update-interval-ms: 3000